# -*- coding: utf-8 -*-
"""modeltraining skin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5debet-QScEdGuRk53uKj_AOqSDKxUE
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/skin_dataset"

datagen = ImageDataGenerator(validation_split=0.2)
train_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

val_data = datagen.flow_from_directory(
    dataset_path,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    subset="validation"
)

import tensorflow as tf
from tensorflow.keras import layers, models

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False  # Freeze pretrained layers

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(train_data.num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.legend(['Train', 'Validation'])
plt.title("Model Accuracy")
plt.show()

print(train_data.samples)
print(val_data.samples)

print(train_data.class_indices)

model.export("skin_model.h5")

from tensorflow.keras.preprocessing import image
import numpy as np

# Load saved model using TFSMLayer for Keras 3 compatibility with SavedModel format
# The saved model name was 'skin_model_tf', and 'serve' is the default endpoint name
model = tf.keras.layers.TFSMLayer("skin_model.h5", call_endpoint='serve')

img_path = "/content/2.jpg"  # Update this path to an existing image file
img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model(img_array)
class_names = list(train_data.class_indices.keys())

print("Predicted:", class_names[np.argmax(prediction)])



